const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),test=require('node:test'),path=require('node:path');
const URLStub=class extends URL {static createObjectURL(){return 'blob:test'} static revokeObjectURL(){}};
const html=fs.readFileSync(path.join(__dirname,'../data/scanner.html'),'utf8'),script=html.match(/<script>([\s\S]*?)<\/script>/)[1];
/** @brief 创建最小浏览器桩，验证上传图片页面不再访问摄像头。 */
function setup(fetchImpl){let requests=0,draws=0;const ctx={fillRect(){},clearRect(){},drawImage(){},beginPath(){},moveTo(){},lineTo(){},closePath(){},stroke(){draws++;}};const make=()=>({value:'',disabled:false,textContent:'',children:[],naturalWidth:640,naturalHeight:480,src:'',getContext:()=>ctx,toDataURL:()=> 'data:image/jpeg;base64,result',toBlob:cb=>cb({size:10000,type:'image/jpeg'}),replaceChildren(){this.children=[]},appendChild(e){this.children.push(e)},removeAttribute(){},addEventListener(){}});const el=Object.fromEntries([...html.matchAll(/id="([^"]+)"/g)].map(m=>[m[1],make()]));const ImageStub=function(){this.onload=()=>{};this.onerror=()=>{};Object.defineProperty(this,'src',{set:()=>queueMicrotask(()=>this.onload())});};const c=vm.createContext({document:{getElementById:id=>el[id],createElement:()=>make()},location:{href:'http://192.168.1.2:81/',origin:'http://192.168.1.2:81'},URL:URLStub,URLApi:{createObjectURL:()=> 'blob:test',revokeObjectURL(){}},Image:ImageStub,performance:{now:()=>100},Date,Math,Number,Blob,AbortController,setTimeout:()=>1,clearTimeout(){},fetch:async(...args)=>{requests++;return fetchImpl(...args)}});vm.runInContext(script,c);return{c,el,requests:()=>requests,draws:()=>draws,run:code=>vm.runInContext(code,c)};}
const code={format:'QR_CODE',text:'WIFI:S:test;',corners:[{x:10,y:20},{x:110,y:20},{x:110,y:120},{x:10,y:120}]};
test('选择单张图片后只发送一次 JPEG 并绘制绿框',async()=>{const s=setup(async()=>({ok:true,json:async()=>({ok:true,frameId:1,width:640,height:480,codes:[code],decodeMs:2,scanMs:3})}));await s.run('selectedFile={}; scanImage()');assert.equal(s.requests(),1);assert.equal(s.draws(),1);assert.match(s.el.status.textContent,/1 个条码/);});
test('服务端错误显示错误且不绘制结果',async()=>{const s=setup(async()=>({ok:false,status:503,json:async()=>({ok:false,error:'解码内存不足'})}));await s.run('selectedFile={}; scanImage()');assert.match(s.el.status.textContent,/解码内存不足/);assert.equal(s.draws(),0);assert.equal(s.requests(),1);});
test('响应帧编号不匹配时拒绝结果',async()=>{const s=setup(async()=>({ok:true,json:async()=>({ok:true,frameId:2,width:640,height:480,codes:[code]})}));await s.run('selectedFile={}; scanImage()');assert.match(s.el.status.textContent,/帧编号/);});
test('越界坐标不会绘制绿框',()=>{const s=setup(async()=>({ok:true,json:async()=>({})}));assert.equal(s.c.validCode({...code,corners:[{x:-1,y:0}]}),false);});

test('请求超时不自动重传同一图片',async()=>{const s=setup(async()=>{const error=new Error('请求超时');error.name='AbortError';throw error;});await s.run('selectedFile={}; scanImage()');assert.equal(s.requests(),1);assert.match(s.el.status.textContent,/请求超时/);assert.equal(s.el.scan.disabled,false);});
